// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, isbn, openlibrary_id, cover_url, category_id, stock, available)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, isbn, openlibrary_id, cover_url, category_id, stock, available, created_at, updated_at
`

type CreateBookParams struct {
	Title         string      `json:"title"`
	Isbn          pgtype.Text `json:"isbn"`
	OpenlibraryID pgtype.Text `json:"openlibrary_id"`
	CoverUrl      pgtype.Text `json:"cover_url"`
	CategoryID    pgtype.UUID `json:"category_id"`
	Stock         int32       `json:"stock"`
	Available     int32       `json:"available"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Isbn,
		arg.OpenlibraryID,
		arg.CoverUrl,
		arg.CategoryID,
		arg.Stock,
		arg.Available,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Isbn,
		&i.OpenlibraryID,
		&i.CoverUrl,
		&i.CategoryID,
		&i.Stock,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, isbn, openlibrary_id, cover_url, category_id, stock, available, created_at, updated_at FROM books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id pgtype.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Isbn,
		&i.OpenlibraryID,
		&i.CoverUrl,
		&i.CategoryID,
		&i.Stock,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, isbn, openlibrary_id, cover_url, category_id, stock, available, created_at, updated_at FROM books ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Isbn,
			&i.OpenlibraryID,
			&i.CoverUrl,
			&i.CategoryID,
			&i.Stock,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2, isbn = $3, cover_url = $4, category_id = $5, stock = $6, updated_at = now()
WHERE id = $1
RETURNING id, title, isbn, openlibrary_id, cover_url, category_id, stock, available, created_at, updated_at
`

type UpdateBookParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Isbn       pgtype.Text `json:"isbn"`
	CoverUrl   pgtype.Text `json:"cover_url"`
	CategoryID pgtype.UUID `json:"category_id"`
	Stock      int32       `json:"stock"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Isbn,
		arg.CoverUrl,
		arg.CategoryID,
		arg.Stock,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Isbn,
		&i.OpenlibraryID,
		&i.CoverUrl,
		&i.CategoryID,
		&i.Stock,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
