// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Bio       pgtype.Text        `json:"bio"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Book struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Isbn          pgtype.Text        `json:"isbn"`
	OpenlibraryID pgtype.Text        `json:"openlibrary_id"`
	CoverUrl      pgtype.Text        `json:"cover_url"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Stock         int32              `json:"stock"`
	Available     int32              `json:"available"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BookAuthor struct {
	BookID   pgtype.UUID `json:"book_id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

type Category struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type Loan struct {
	ID         pgtype.UUID        `json:"id"`
	BookID     pgtype.UUID        `json:"book_id"`
	MemberID   pgtype.UUID        `json:"member_id"`
	BorrowedAt pgtype.Timestamptz `json:"borrowed_at"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	ReturnedAt pgtype.Timestamptz `json:"returned_at"`
	Status     string             `json:"status"`
	FineAmount pgtype.Numeric     `json:"fine_amount"`
}

type Member struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
